version: 0.2

env:
  variables:
    REPORT_BUCKET: "arjit-grype-report-s3"     # S3 bucket for Grype HTML report
    BUILD_BUCKET: "arjit-s3"                   # S3 bucket for application build

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - echo "🔧 Installing dependencies..."
      - npm install
      - echo "⬇️ Installing Grype vulnerability scanner..."
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      - echo "🔍 Running Grype vulnerability scan..."
      # Generate JSON report for HTML conversion
      - grype dir:. --output json > grype-report.json || true

      - echo "📊 Converting Grype JSON report to HTML..."
      - python3 grype_to_html.py

      - echo "📤 Uploading Grype HTML report to S3..."
      - aws s3 rm s3://$REPORT_BUCKET/grype-report.html || true
      - aws s3 cp grype-report.html s3://$REPORT_BUCKET/

      # Fail the build if vulnerabilities of medium severity or higher are found
      - echo "⚙️ Checking for medium or higher vulnerabilities..."
      - |
        grype dir:. --fail-on medium --output table | tee grype-scan.log
        SCAN_EXIT_CODE=${PIPESTATUS[0]}
        if [ $SCAN_EXIT_CODE -ne 0 ]; then
          echo "❌ Vulnerabilities found at or above medium severity. Failing pipeline..."
          exit 1
        else
          echo "✅ No medium or higher vulnerabilities found."
        fi

  build:
    commands:
      - echo "🚀 Building the project..."
      - npm run build

  post_build:
    commands:
      - echo "📦 Uploading build artifacts to S3..."
      - aws s3 sync build/ s3://$BUILD_BUCKET --delete
      - echo "🧹 Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E3PIQ3TRAQXUY0 --paths "/*"
      - echo "✅ Build and vulnerability scan completed successfully!"

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
