version: 0.2

env:
  variables:
    REPORT_BUCKET: "arjit-grype-report-s3"   # S3 bucket for HTML report

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - echo "🔧 Installing dependencies..."
      - npm install
      - echo "⬇️ Installing Grype vulnerability scanner..."
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - grype version
      - echo "✅ Grype installed successfully."

  pre_build:
    commands:
      - echo "=========================================="
      - echo "🔍 Step 1: Running vulnerability scan with Grype"
      - echo "=========================================="

      # Run Grype and create JSON report
      - grype dir:. --output json > grype-report.json || true

      - echo "📁 Checking if JSON report exists..."
      - |
        if [ ! -f "grype-report.json" ]; then
          echo "❌ grype-report.json not found — scan failed!"
          exit 1
        else
          echo "✅ grype-report.json generated successfully."
        fi

      - echo "=========================================="
      - echo "🧾 Step 2: Converting JSON report to HTML"
      - echo "=========================================="

      # Ensure Python script exists before running
      - |
        if [ ! -f "grype_to_html.py" ]; then
          echo "❌ grype_to_html.py not found in the source directory!"
          exit 1
        fi

      # Run Python script to generate HTML report
      - python3 grype_to_html.py

      - echo "=========================================="
      - echo "📤 Step 3: Uploading HTML report to S3 bucket"
      - echo "=========================================="

      # Upload HTML report to S3 bucket
      - |
        if [ -f "grype-report.html" ]; then
          aws s3 cp grype-report.html s3://$REPORT_BUCKET/
          echo "✅ HTML report uploaded to s3://$REPORT_BUCKET/"
        else
          echo "❌ grype-report.html not found — skipping upload!"
          exit 1
        fi

  build:
    commands:
      - echo "✅ Grype scan and HTML report generation completed successfully."

artifacts:
  files:
    - grype-report.html
